---
version: 0.2
run-as: root
phases:
  install:
    on-failure: ABORT
    commands:
      - apt-get update -q
      - apt-get install -qy unzip
      - curl --silent https://releases.hashicorp.com/packer/1.7.9/packer_1.7.9_linux_amd64.zip -o /tmp/packer.zip
      - unzip /tmp/packer.zip -d /usr/local/bin
      - pip install git+https://github.com/janus-anderwelt/aws-amicleaner.git
  build:
    on-failure: ABORT
    commands:
      - cd $CODEBUILD_SRC_DIR/packer && packer build -color=false debian_wireguard.json
  post_build:
    commands:
      - aws ec2 describe-images --owners self --filters 'Name=name,Values=packer-debian-wireguard-thrift*'
      - amicleaner -f --keep-previous 1
